apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpod
  namespace: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpod
  template:
    metadata:
      labels:
        app: testpod
    spec:
      containers:
        - name: main
          image: ghcr.io/simonrw/docker-debug:main
          command: ["sleep", "infinity"]
          env:
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: AWS_DEFAULT_REGION
              value: us-east-1
