apiVersion: v1
kind: Service
metadata:
  name: ts-argocd-server
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8080
      name: https
  type: LoadBalancer
  loadBalancerClass: tailscale
